// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RepositoryDetail: typeof import('./src/components/views/RepositoryDetail.vue')['default']
    RepositorySearch: typeof import('./src/components/views/RepositorySearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VForm: typeof import('vuetify/lib')['VForm']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VResponsive: typeof import('vuetify/lib')['VResponsive']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
